# Generated by Django 4.0.4 on 2022-05-10 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calibre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desc_calibre', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ObjetoTipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_de_objeto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('objeto_tipo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.objetotipo')),
            ],
        ),
        migrations.CreateModel(
            name='Municao',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='estoque.objeto')),
                ('marca', models.CharField(max_length=255)),
                ('modelo', models.CharField(max_length=255)),
                ('valor_estimado', models.FloatField()),
                ('calibre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.calibre')),
            ],
        ),
        migrations.CreateModel(
            name='Arma',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='estoque.objeto')),
                ('marca', models.CharField(max_length=255)),
                ('modelo', models.CharField(max_length=255)),
                ('quantidade_de_tiros', models.IntegerField()),
                ('valor_estimado', models.FloatField()),
                ('imagem', models.ImageField(upload_to='')),
                ('calibre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.calibre')),
            ],
        ),
    ]
