# Generated by Django 4.0.4 on 2022-05-13 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arma',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='armas_images'),
        ),
    ]
