# Generated by Django 4.0.4 on 2022-05-11 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibre',
            name='desc_calibre',
            field=models.CharField(max_length=255),
        ),
    ]
