# Generated by Django 4.0.4 on 2022-05-12 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arma',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='arma',
            name='marca',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='arma',
            name='modelo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='arma',
            name='quantidade_de_tiros',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arma',
            name='valor_estimado',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calibre',
            name='desc_calibre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='municao',
            name='marca',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='municao',
            name='modelo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='municao',
            name='valor_estimado',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='objeto_tipo_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estoque.objetotipo'),
        ),
        migrations.AlterField(
            model_name='objetotipo',
            name='tipo_de_objeto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
