# Generated by Django 4.0.4 on 2022-05-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_alter_arma_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arma',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='armas_imagens'),
        ),
    ]
