# Generated by Django 4.0.4 on 2022-05-11 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_alter_calibre_desc_calibre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arma',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='arma',
            name='marca',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='arma',
            name='modelo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='arma',
            name='quantidade_de_tiros',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arma',
            name='valor_estimado',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='municao',
            name='marca',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='municao',
            name='modelo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='municao',
            name='valor_estimado',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
